ace:
  name: Ace
  short_name: A
  value: 13
  suit: spades

king:
  name: King
  short_name: K
  value: 12
  suit: spades

queen:
  name: Queen
  short_name: Q
  value: 11
  suit: spades

jack:
  name: Jack
  short_name: J
  value: 10
  suit: spades

10:
  name: 10
  short_name: 10
  value: 9
  suit: spades

9:
  name: 9
  short_name: 9
  value: 8
  suit: spades

8:
  name: 8
  short_name: 8
  value: 7
  suit: spades

7:
  name: 7
  short_name: 7
  value: 6
  suit: spades

6:
  name: 6
  short_name: 6
  value: 5
  suit: spades

5:
  name: 5
  short_name: 5
  value: 4
  suit: spades

4:
  name: 4
  short_name: 4
  value: 3
  suit: spades

3:
  name: 3
  short_name: 3
  value: 2
  suit: spades

2:
  name: 2
  short_name: 2
  value: 1
  suit: spades

ace:
  name: Ace
  short_name: A
  value: 13
  suit: hearts

king:
  name: King
  short_name: K
  value: 12
  suit: hearts

queen:
  name: Queen
  short_name: Q
  value: 11
  suit: hearts

jack:
  name: Jack
  short_name: J
  value: 10
  suit: hearts

10:
  name: 10
  short_name: 10
  value: 9
  suit: hearts

9:
  name: 9
  short_name: 9
  value: 8
  suit: hearts

8:
  name: 8
  short_name: 8
  value: 7
  suit: hearts

7:
  name: 7
  short_name: 7
  value: 6
  suit: hearts

6:
  name: 6
  short_name: 6
  value: 5
  suit: hearts

5:
  name: 5
  short_name: 5
  value: 4
  suit: hearts

4:
  name: 4
  short_name: 4
  value: 3
  suit: hearts

3:
  name: 3
  short_name: 3
  value: 2
  suit: hearts

2:
  name: 2
  short_name: 2
  value: 1
  suit: hearts

ace:
  name: Ace
  short_name: A
  value: 13
  suit: diamonds

king:
  name: King
  short_name: K
  value: 12
  suit: diamonds

queen:
  name: Queen
  short_name: Q
  value: 11
  suit: diamonds

jack:
  name: Jack
  short_name: J
  value: 10
  suit: diamonds

10:
  name: 10
  short_name: 10
  value: 9
  suit: diamonds

9:
  name: 9
  short_name: 9
  value: 8
  suit: diamonds

8:
  name: 8
  short_name: 8
  value: 7
  suit: diamonds

7:
  name: 7
  short_name: 7
  value: 6
  suit: diamonds

6:
  name: 6
  short_name: 6
  value: 5
  suit: diamonds

5:
  name: 5
  short_name: 5
  value: 4
  suit: diamonds

4:
  name: 4
  short_name: 4
  value: 3
  suit: diamonds

3:
  name: 3
  short_name: 3
  value: 2
  suit: diamonds

2:
  name: 2
  short_name: 2
  value: 1
  suit: diamonds

ace:
  name: Ace
  short_name: A
  value: 13
  suit: clubs

king:
  name: King
  short_name: K
  value: 12
  suit: clubs

queen:
  name: Queen
  short_name: Q
  value: 11
  suit: clubs

jack:
  name: Jack
  short_name: J
  value: 10
  suit: clubs

10:
  name: 10
  short_name: 10
  value: 9
  suit: clubs

9:
  name: 9
  short_name: 9
  value: 8
  suit: clubs

8:
  name: 8
  short_name: 8
  value: 7
  suit: clubs

7:
  name: 7
  short_name: 7
  value: 6
  suit: clubs

6:
  name: 6
  short_name: 6
  value: 5
  suit: clubs

5:
  name: 5
  short_name: 5
  value: 4
  suit: clubs

4:
  name: 4
  short_name: 4
  value: 3
  suit: clubs

3:
  name: 3
  short_name: 3
  value: 2
  suit: clubs

2:
  name: 2
  short_name: 2
  value: 1
  suit: clubs


