
Knight:
  num: 14
  desc: Move the Robber. Steal 1 resource card from the owner of an adjacent settlement or city.

Victory Point:
  num: 5
  desc: 1 Victory Point!

Road Building:
  num: 2
  desc: Place 2 new roads as if you had just built them.

Monopoly:
  num: 2
  desc: When you play this card, announce 1 type of resource. All other players must give you all their resource cards of that type.

Year of Plenty:
  num: 2
  desc: Take any 2 resources from the bank. Add them to your hand. They can be 2 of the same or 2 different resources.